In [1]:
import numpy as np

In [2]:
#Creating a array
array=np.array([1,2,3,4,5,6])
print(array)
type(array)
array.shape

[1 2 3 4 5 6]


(6,)

In [3]:
arr = np.array((1, 2, 3, 4, 5))
print(arr)
type(arr)
arr.shape

[1 2 3 4 5]


(5,)

In [4]:
two_d_arr=np.array([[1,2,3],[4,5,6]])
print(two_d_arr)
print(type(two_d_arr))
print(two_d_arr.shape)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)


In [5]:
three_d_arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(three_d_arr)
print(type(three_d_arr))
print(three_d_arr.shape)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
<class 'numpy.ndarray'>
(2, 2, 3)


In [6]:
#Check how many dimensions the arrays have
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print('number of dimensions of array a:',a.ndim,a.dtype)
print('number of dimensions of array b:',b.ndim,b.dtype)
print('number of dimensions of array c:',c.ndim,c.dtype)
print('number of dimensions of array d:',d.ndim,d.dtype)

number of dimensions of array a: 0 int32
number of dimensions of array b: 1 int32
number of dimensions of array c: 2 int32
number of dimensions of array d: 3 int32


In [7]:
#Access Array Elements
b = np.array([1, 2, 3, 4, 5])
print(b[0])
print(b[1])
print(b[3])
#concatinating array elements
print(b[0]+b[1])

1
2
4
3


In [8]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)
#accessing 2nd element in first row
print("2nd element in first row",arr[0][2])
#accessing 4th element in second row
print("4th element in second row",arr[1][3])
#accessing 5th element on 2nd row
print('5th element on 2nd row: ', arr[1, 4])


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2nd element in first row 3
4th element in second row 9
5th element on 2nd row:  10


In [9]:
arr = np.array([["a","b","c","d","e"], [6,7,8,9,10]])
print(arr[1,2])
print(arr[0,1:4])
print(arr[0][0:4])
#step
print(arr[0][0:4:2])
#From both elements, return index 2
arr = np.array([["a","b","c","d","e"], [6,7,8,9,10]])
print(arr[0:2,2])


8
['b' 'c' 'd']
['a' 'b' 'c' 'd']
['a' 'c']
['c' '8']


In [10]:
#Return every other element from the entire array:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[::2])

[1 3 5 7]


In [11]:
#From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2,1:4])

[[2 3 4]
 [7 8 9]]


In [12]:
#Get the data type of an array object:
#u- unicode string
arr2 = np.array(["a","b","c","d","e"])
arr3=np.array([1,2,3,4,5,6])
print(arr2.dtype)
print(arr3.dtype)

<U1
int32


In [13]:
#Change data type in array
array1=np.array([1.0,2.3,3.5,4.4,5.9,6.6,7.3], dtype=int)
print(array1)
array2=np.array(["1","2","3","4","5"])
array2=array2.astype(int)
print(array2)

[1 2 3 4 5 6 7]
[1 2 3 4 5]


In [14]:
#Change data type from integer to boolean:
arr = np.array([1, 0, 3])
new_arr=arr.astype(bool)
new_arr

array([ True, False,  True])

In [15]:
#Make a copy, change the original array, and display both arrays:
arr1=np.array([1,"sagar",3.6,"rohith",10,True])
arr2=np.copy(arr1)
arr1[2]="revati"
print("Original array -",arr1)
print("Copy of original array",arr2)

Original array - ['1' 'sagar' 'revati' 'rohith' '10' 'True']
Copy of original array ['1' 'sagar' '3.6' 'rohith' '10' 'True']


In [16]:
#Make a view, change the view, and display both arrays:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [18]:
#3 dimension array
array=np.array([[1,2,3,4,5],[11,12,13,14,15],[45,50,55,60,65]])
array.shape

(3, 5)

In [21]:
arr1=np.array([1,2,3,4,5],ndmin=3)
print(arr1)
print(arr1.shape)

[[[1 2 3 4 5]]]
(1, 1, 5)


In [26]:
#reshape the array
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr.shape)
#converting 1D array to 4*3-4 array with 3 items each
arr2=arr.reshape(4,3)
print(arr2)
print("Reshape of array",arr2.shape)

(12,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Reshape of array (4, 3)


In [27]:
#converting 1D array to 3D array
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr1=arr.reshape(2,2,3)
arr1

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])