In [1]:
import numpy as np

In [2]:
# #Iterating Arrays
# Iterating means going through elements one by one.
# As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.
# If we iterate on a 1-D array it will go through each element one by one.

In [3]:
#Iterating 1D array
arr=np.array([1,2,3,4,5])
for x in arr:
    print(x)

1
2
3
4
5


In [8]:
#Iterating 2D array
arr=np.array([[1,2,3,4,5],[6,5,4,3,2,1]],dtype=object)
for x in arr:
    print(x)

[1, 2, 3, 4, 5]
[6, 5, 4, 3, 2, 1]


In [9]:
#Iterate on each scalar element of the 2-D array:
arr=np.array([[1,2,3,4,5],[6,5,4,3,2,1]],dtype=object)
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6
5
4
3
2
1


In [10]:
#Iterate on the elements of the following 3-D array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [14]:
#Iterate on each scalar element of the 3-D array:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [15]:
# Iterating Arrays Using nditer()
# The function nditer() is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration, lets go through it with examples.
# Iterating on Each Scalar Element
# In basic for loops, iterating through each scalar of an array we need to use n for loops which can be difficult to write for arrays with very high dimensionality.

In [16]:
#iterating using nditer method in numpy
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [18]:
# Iterating Array With Different Data Types
# We can use op_dtypes argument and pass it the expected datatype to change the datatype of elements while iterating.
# NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered'].
arr = np.array([1, 2, 3])
for x in np.nditer(arr,flags=['buffered'],  op_dtypes=['S']):
    print(x)

b'1'
b'2'
b'3'


In [19]:
#Iterate through every scalar element of the 2D array skipping element with step 2
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
    print(x)

1
3
5
7


In [20]:
# #
# Enumerated Iteration Using ndenumerate()
# Enumeration means mentioning sequence number of somethings one by one
arr=np.array([0,1,2,3,4,5])
for index,x in np.ndenumerate(arr):
    print(index,x)

(0,) 0
(1,) 1
(2,) 2
(3,) 3
(4,) 4
(5,) 5


In [22]:
#2D array
arr=np.array([[1,2,3,4,5],[4,5,6,7,8,9]],dtype=object)
for indx,x in np.ndenumerate(arr):
    print(indx,x)

(0,) [1, 2, 3, 4, 5]
(1,) [4, 5, 6, 7, 8, 9]


In [25]:
# Joining NumPy Arrays using numpy concatenate method
#join along with rows
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
new_arr=np.concatenate((arr1,arr2))
new_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
#join along with column axis=1
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[6,7,8],[9,10,11]])
new_arr=np.concatenate((arr1,arr2),axis=1)
new_arr

array([[ 1,  2,  3,  6,  7,  8],
       [ 4,  5,  6,  9, 10, 11]])

In [ ]:
# Joining Arrays Using Stack Functions
# Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

# We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.

# We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.

In [32]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
n_a=np.stack((arr1,arr2),axis=1)
n_a

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [ ]:
# Stacking Along Rows
# NumPy provides a helper function: hstack() to stack along rows.

In [33]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
x=np.hstack((arr1,arr2))
x

array([1, 2, 3, 4, 5, 6])

In [ ]:
# Stacking Along columns
# NumPy provides a helper function: vstack() to stack along columns

In [34]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
x=np.vstack((arr1,arr2))
x

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
# Stacking Along Height (depth)
# NumPy provides a helper function: dstack() to stack along height, which is the same as depth.

In [39]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
x=np.dstack((arr1,arr2))
x

array([[[1, 4],
        [2, 5],
        [3, 6]]])

In [40]:
# Splitting NumPy Arrays
# Splitting is reverse operation of Joining.

# Joining merges multiple arrays into one and Splitting breaks one array into multiple.

# We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits

In [42]:
arr=np.arange(0,10,2)
print(arr)
n_p=np.array_split(arr,3)
print(n_p)


[0 2 4 6 8]
[array([0, 2]), array([4, 6]), array([8])]


In [44]:
arr=np.arange(0,50,5)
print(arr)
n_p=np.array_split(arr,4)
n_p

[ 0  5 10 15 20 25 30 35 40 45]


[array([ 0,  5, 10]), array([15, 20, 25]), array([30, 35]), array([40, 45])]

In [45]:
# Searching Arrays
# You can search an array for a certain value, and return the indexes that get a match.

# To search an array, use the where() method.

In [52]:
#in this it returns the tuple where 2 is present at the index
# Which means that the value 4 is present at index 1,2,4,6 and 9.
arr=np.array([1,2,2,5,2,7,2,4,1,2],dtype=int)
x=np.where(arr==2)
x

(array([1, 2, 4, 6, 9], dtype=int64),)

In [53]:
#Find the indexes where the values are odd:
arr=np.arange(0,10)
new=np.where(arr%2==1)
new

(array([1, 3, 5, 7, 9], dtype=int64),)

In [60]:
#Find the indexes where the names are in even index:
arr=np.array(["A","B","C","D","E","F","G","H","I","J","K","L","M","N"],dtype=object)
new=np.where(arr==(["H"]))
new
# H is in the 7 th index

(array([7], dtype=int64),)

In [61]:
# Search Sorted
# There is a method called searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order
arr=np.array(["A","B","C","D","E","F","G","H","I","J","K","L","M","N"],dtype=object)
new=np.searchsorted(arr,"E")
new
#E is at 4th index

4

In [62]:
#Find the indexes where the value E should be inserted, starting from the right:
arr=np.array(["A","B","C","D","E","F","G","H","I","J","K","L","M","N"],dtype=object)
new=np.searchsorted(arr,"E", side='right')
new
#E is at 4th index

5

In [63]:
#Sorting of array using numpy sort() method
arr=np.array([0,25,8,44,6,888,664,2615,3,4,5])
new_arr=np.sort(arr)
new_arr

array([   0,    3,    4,    5,    6,    8,   25,   44,  664,  888, 2615])

In [64]:
#alphabatically sorting
arr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [65]:
#sort bool value
arr = np.array([True, False, True])
print(np.sort(arr))

[False  True  True]


In [66]:
# Sorting a 2-D Array
# If you use the sort() method on a 2-D array, both arrays will be sorted:
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]
